# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dm_lm_bvs <- function(iterations, thin, alpha, y, z, x, phi, psi, temp_cc, temp_uu, sigma2_alpha, zeta, xi, sigma2_phi, a, b, a_0, b_0, h_alpha, h_beta, a_m, b_m, prior, Omega, G, Var, S, v0, v1, a_G, b_G, pie, lambda) {
    .Call(`_MicroBVS_dm_lm_bvs`, iterations, thin, alpha, y, z, x, phi, psi, temp_cc, temp_uu, sigma2_alpha, zeta, xi, sigma2_phi, a, b, a_0, b_0, h_alpha, h_beta, a_m, b_m, prior, Omega, G, Var, S, v0, v1, a_G, b_G, pie, lambda)
}

dm_bvs <- function(iterations, thin, alpha, z, x, phi, temp_cc, temp_uu, sigma2_alpha, zeta, sigma2_phi, prior, a, b, Omega, G, Var, S, v0, v1, a_G, b_G, pie, lambda) {
    .Call(`_MicroBVS_dm_bvs`, iterations, thin, alpha, z, x, phi, temp_cc, temp_uu, sigma2_alpha, zeta, sigma2_phi, prior, a, b, Omega, G, Var, S, v0, v1, a_G, b_G, pie, lambda)
}

wang <- function(iterations, thin, x, Omega, G, Var, S, v0, v1, pie, lambda) {
    .Call(`_MicroBVS_wang`, iterations, thin, x, Omega, G, Var, S, v0, v1, pie, lambda)
}

DTMbvs <- function(iterations, thin, prior, x, branch_location, node_children_pointer, branch_counts, subtree_counts, alpha, phi, zeta, sigma2_alpha, sigma2_phi, aa, bb, Omega, G, Var, S, v0, v1, a_G, b_G, pie, lambda) {
    .Call(`_MicroBVS_DTMbvs`, iterations, thin, prior, x, branch_location, node_children_pointer, branch_counts, subtree_counts, alpha, phi, zeta, sigma2_alpha, sigma2_phi, aa, bb, Omega, G, Var, S, v0, v1, a_G, b_G, pie, lambda)
}

ilr_fun_cpp <- function(x) {
    .Call(`_MicroBVS_ilr_fun_cpp`, x)
}

log_post <- function(iterations, alpha, y, z, x, phi, psi, sigma2_alpha, zeta, xi, sigma2_phi, a, b, a_0, b_0, h_alpha, h_beta, a_m, b_m) {
    .Call(`_MicroBVS_log_post`, iterations, alpha, y, z, x, phi, psi, sigma2_alpha, zeta, xi, sigma2_phi, a, b, a_0, b_0, h_alpha, h_beta, a_m, b_m)
}

loo_prep <- function(y, psi, xi, a_0, b_0, h_alpha, h_beta) {
    .Call(`_MicroBVS_loo_prep`, y, psi, xi, a_0, b_0, h_alpha, h_beta)
}

log_zeta_pj_cpp <- function(t_pj, a, b) {
    .Call(`_MicroBVS_log_zeta_pj_cpp`, t_pj, a, b)
}

dm_lm_mediation <- function(iterations, thin, alpha, y, z, x, phi, psi, temp_cc, temp_uu, sigma2, sigma_alpha, sigma_beta, zeta, xi, beta, sigma2_phi, a, b, a_0, b_0, h_alpha, h_beta, a_m, b_m) {
    .Call(`_MicroBVS_dm_lm_mediation`, iterations, thin, alpha, y, z, x, phi, psi, temp_cc, temp_uu, sigma2, sigma_alpha, sigma_beta, zeta, xi, beta, sigma2_phi, a, b, a_0, b_0, h_alpha, h_beta, a_m, b_m)
}

